version: '3.8'

services:
  habit.api:
    container_name: habit.api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - habit.db
      - habit.minio
      - habit.rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: Pass@habit
      ASPNETCORE_Kestrel__Certificates__Default__Path: .aspnet/https/habit.pfx
    restart: always
    
  habit.db:
    container_name: habit.db
    image: postgres:latest
    environment:
      POSTGRES_DB: habit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  habit.minio:
    container_name: habit.minio
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ofBo7Axzqli4AQssLN5l
      MINIO_SECRET_KEY: 5gMJcLitNIOAyocrp8Y7dapU9b585fFeFbL8wU1n
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    volumes:
      - ./.containers/minio:/data
  
  habit.rabbitmq:
    container_name: habit.rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: esm3threeweb3
        RABBITMQ_DEFAULT_PASS: L9cardrive
    volumes:
      - ./.containers/rabbitmq:/var/lib/rabbitmq